# Static analysis configuration. Run with `flutter analyze`.
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "build/**"
  errors:
    todo: ignore

linter:
  rules:
    - avoid_print
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_final_locals
    - prefer_single_quotes
    - sort_child_properties_last
    - use_key_in_widget_constructors
