"""Additional original reading passages and their comprehension questions.

This module supplements passages.py with more original prose written for this
project. Each single passage in PASSAGES2 yields five questions (main idea,
inference, text structure/purpose, words-in-context, command of evidence).
Paired passages in PAIRED2 yield cross-text questions.

As in passages.py, distractors are written to be full, plausible statements of
length comparable to the key, so the correct answer does not stand out by length.
The builders shuffle option order (seeded) so the correct choice is not always in
the same position. The correct_index values here are deliberately varied across
0, 1, 2, and 3.

A question spec is (prompt, [opt0..opt3], correct_index, [rat0..rat3], explanation).
"""
from __future__ import annotations

PASSAGES2 = [
    {
        "id": 'coral_clock', "title": 'The Coral That Keeps Time',
        "text": (
            "A coral skeleton grows in fine bands, much like the rings of a tree. In bright, warm months the coral lays down thick layers; in cooler, dimmer months the layers thin. By slicing a coral and counting these bands, researchers can read a record of past seasons stretching back centuries. Even better, the chemistry trapped in each band hints at the water's temperature when it formed. So a single old coral can serve as a kind of diary, written not in words but in stone, recording conditions long before anyone thought to measure them. The challenge is learning to read a language no one designed to be read."),
        'main_idea': (
            'Which choice best states the main idea of the passage?',
            ['Coral bands preserve a long, readable record of past ocean conditions.',
              'Coral grows faster than trees and so makes a more accurate calendar.',
              'Researchers prefer studying coral because it is easier than studying trees.',
              'Warm water is the only factor that determines how thick a coral band grows.'],
            0,
            ['Correct. The passage centers on how coral bands record and reveal past conditions.',
              'The passage compares coral to trees but never claims it grows faster.',
              'No claim of relative ease over tree study is made.',
              'Chemistry and season both matter; warmth is not called the only factor.'],
            'The passage frames the coral as a centuries-long record that researchers learn to read.'),
        'inference': (
            'It can reasonably be inferred that the coral record is valuable mainly because it',
            ['remains perfectly readable without any special training',
              'preserves data from times before people kept measurements',
              'can be created quickly in a laboratory whenever needed',
              'shows exactly which species of fish lived nearby each year'],
            1,
            ['The passage calls reading it a challenge requiring effort.',
              "Correct. The passage stresses conditions recorded 'before anyone thought to measure them.'",
              'Coral grows over centuries; it is not made quickly in a lab.',
              'Nearby fish species are never mentioned.'],
            'Its value lies in capturing conditions from before instrument records existed.'),
        'structure': (
            'Which choice best describes the overall structure of the passage?',
            ['It argues that coral reefs are endangered and must be legally protected.',
              'It traces the life cycle of a single coral colony from birth to death.',
              'It compares coral to a familiar record, explains the method, then notes a difficulty.',
              'It lists the steps a diver should take to collect a coral sample safely.'],
            2,
            ['The passage makes no protection argument.',
              "It does not trace a colony's life cycle.",
              'Correct. The passage moves from a tree-ring analogy to the band-reading method to a closing challenge.',
              'No collection steps are given.'],
            'The passage proceeds from analogy to method to remaining difficulty.'),
        'wic': (
            'As used in the passage, the word “record” most nearly means',
            ['the best result ever achieved',
              'a flat disc that plays music',
              'to set down in writing for the first time',
              'a preserved account of past events'],
            3,
            ["No achievement or 'best result' is meant here.",
              'The musical-disc sense does not fit the context.',
              "The noun sense, not the verb 'to record,' fits this use.",
              'Correct. The coral preserves an account of past seasons.'],
            "Here 'a record of past seasons' means a preserved account of them."),
        'evidence': (
            'Which detail best supports the idea that coral bands reveal past water temperature?',
            ['the statement that reading the bands is like reading an unfamiliar language',
              "the statement that the chemistry trapped in each band hints at the water's temperature",
              'the statement that a coral skeleton grows in fine bands like tree rings',
              'the statement that the record can stretch back several centuries'],
            1,
            ['The reading-difficulty image does not establish temperature.',
              'Correct. The trapped chemistry directly links the bands to past temperature.',
              'The tree-ring comparison concerns growth, not temperature.',
              "The record's length does not address temperature."],
            'Temperature is supported specifically by the trapped-chemistry detail.'),
    },
    {
        "id": 'canal_locks', "title": 'Stairs for Boats',
        "text": (
            'Rivers do not run level, and for centuries that simple fact blocked boats from traveling far inland. The lock changed things. A lock is a chamber with gates at each end; a boat enters, the gates close, and water is let in or drained out until the boat rises or falls to the next stretch of river. String several locks together, and a vessel can climb a hillside the way a person climbs a staircase. The engineering is humble, relying on nothing more exotic than gravity and patience, yet it knit distant towns into trading partners and turned shallow rivers into highways of commerce.'),
        'main_idea': (
            'Which choice best states the central idea of the passage?',
            ['Locks required rare and costly materials that few towns could ever afford.',
              'Boats could always travel freely inland long before the lock was invented.',
              'Canal locks let boats overcome changes in elevation, opening inland trade.',
              'Rivers were once the fastest possible way to move goods over long distances.'],
            2,
            ['The passage stresses humble means, not rare materials.',
              'The passage says elevation once blocked inland travel.',
              'Correct. The passage explains how locks conquer elevation and thereby expand trade.',
              'The passage does not rank rivers as the fastest route.'],
            "The lock's purpose and its effect on inland commerce are the passage's focus."),
        'inference': (
            'It can reasonably be inferred that before locks existed, inland water travel was',
            ['faster than any later canal-based travel',
              'carried out mostly by very large ocean ships',
              'preferred by traders over every overland route',
              "limited by differences in a river's elevation"],
            3,
            ['No claim is made that earlier travel was faster.',
              'Ocean ships are never mentioned.',
              'Trader preferences for routes are not discussed.',
              "Correct. The passage says elevation 'blocked boats from traveling far inland.'"],
            'The opening establishes elevation as the obstacle locks later removed.'),
        'structure': (
            'The author compares a series of locks to a staircase mainly to',
            ['help readers picture how boats move up or down in steps',
              'argue that staircases should be built beside every river',
              'list the materials needed to construct a single lock chamber',
              'prove that climbing stairs is harder than operating a lock'],
            0,
            ['Correct. The staircase image clarifies the step-by-step rise and fall of boats.',
              'No argument about building staircases appears.',
              'The comparison is not a materials list.',
              'The passage does not compare difficulty of stairs and locks.'],
            'The staircase analogy is an explanatory image for stepwise elevation change.'),
        'wic': (
            'As used in the passage, the word “knit” most nearly means',
            ['furrowed in worry',
              'healed a broken bone',
              'bound together',
              'wove with yarn'],
            2,
            ["The 'furrowed brow' sense does not fit.",
              'The bone-healing sense does not fit this context.',
              'Correct. Locks bound distant towns together as trading partners.',
              'No literal yarn is involved.'],
            "To 'knit towns into trading partners' means to bind them together."),
        'evidence': (
            'Which detail best supports the claim that locks rely on simple means?',
            ['the statement that a boat enters a chamber with gates at each end',
              'the statement that distant towns became trading partners',
              'the statement that shallow rivers became highways of commerce',
              'the statement that the lock relies on nothing more exotic than gravity and patience'],
            3,
            ['The chamber description explains how a lock works, not its simplicity.',
              'Trading partnerships are an effect, not evidence of simplicity.',
              'Rivers becoming highways is an effect, not evidence of simplicity.',
              "Correct. 'Nothing more exotic than gravity and patience' directly shows simple means."],
            "Simplicity is supported by the 'gravity and patience' detail."),
    },
    {
        "id": 'lichen_pioneer', "title": 'First on the Rock',
        "text": (
            'When a bare rock is left exposed, the first life to arrive is often a lichen, a strange partnership of fungus and alga living as one. The fungus grips the stone and gathers moisture; the alga, sheltered inside, makes food from sunlight. Together they need no soil at all. As a lichen grows, it slowly releases acids that crack the rock surface, and its dead tissue mixes with grit to form the first thin crumbs of soil. Years later, mosses and small plants can take root in that beginning. The lichen will likely be crowded out by the very community it made possible, an unsung founder of the green world that follows.'),
        'main_idea': (
            'Which choice best states the central idea of the passage?',
            ['Lichens prepare bare rock for later plants by helping form the first soil.',
              'Lichens are the only living things able to survive on exposed rock surfaces.',
              'Mosses and small plants arrive on bare rock before any lichen does.',
              'Lichens compete with one another for the limited sunlight on a rock.'],
            0,
            ['Correct. The passage shows lichens building the soil that lets later plants grow.',
              'The passage does not claim lichens are the only rock survivors.',
              'The passage says lichens come first and mosses follow.',
              'Competition among lichens is not the focus.'],
            'The passage frames the lichen as a pioneer that makes soil for what comes next.'),
        'inference': (
            'It can reasonably be inferred that, without lichens, a bare rock would',
            ['produce richer soil than rock that lichens have colonized',
              'take much longer to support mosses and small plants',
              'remain forever incapable of supporting any plant life',
              'be colonized first by large trees instead of by mosses'],
            1,
            ['Lichen-free rock would have less, not richer, soil.',
              'Correct. Since lichens form the first soil, their absence would slow later plant arrival.',
              'The passage does not say plant life would be forever impossible.',
              'Large trees colonizing first contradicts the described order.'],
            'Because lichens create the first soil, their absence would delay later colonizers.'),
        'structure': (
            'The passage is organized mainly by',
            ['describing the lichen, its action on rock, and the succession it enables',
              'comparing two rival kinds of lichen growing on the same stone',
              'listing, step by step, how to identify a lichen in the field',
              'arguing that bare rock should be protected from all disturbance'],
            0,
            ['Correct. It moves from what a lichen is, to how it breaks rock, to later plants.',
              'No two lichens are compared.',
              'No identification steps are given.',
              'The passage makes no protection argument.'],
            'The structure runs from description to action to ecological succession.'),
        'wic': (
            'As used in the passage, the word “grips” most nearly means',
            ['complains about',
              'holds firmly to',
              'understands fully',
              'seizes with fear'],
            1,
            ['Complaining is not the sense here.',
              'Correct. The fungus holds firmly to the stone.',
              "The 'comprehends' sense does not fit a fungus on rock.",
              'No fear is involved.'],
            "The fungus that 'grips the stone' holds firmly to it."),
        'evidence': (
            'Which detail best supports the claim that lichens help create soil?',
            ['the statement that the alga makes food from sunlight while sheltered inside',
              'the statement that the lichen is later crowded out by the community it enabled',
              'the statement that lichens release acids that crack rock and leave tissue that mixes into grit',
              'the statement that a lichen is a partnership of fungus and alga living as one'],
            2,
            ["The alga's feeding explains survival, not soil formation.",
              'Being crowded out is the outcome, not the soil-making process.',
              'Correct. Cracking rock and leaving tissue that mixes into grit directly forms soil.',
              'The partnership detail explains what a lichen is, not soil-making.'],
            'Soil formation is supported by the acid-and-tissue detail.'),
    },
    {
        "id": 'spice_route', "title": 'The Price of Pepper',
        "text": (
            'There was a time when a handful of black pepper could rival a handful of silver. The spice grew only in distant lands, and by the time it reached a European market it had passed through many hands, each adding a markup. Merchants guarded their routes jealously and spread tall tales about how spices were harvested, partly to discourage rivals. The high prices drove sailors to seek their own sea paths to the source, voyages that redrew the map of the world. In the end, the very abundance those voyages produced made spices ordinary, and the fortunes built on rarity quietly dissolved.'),
        'main_idea': (
            'Which choice best states the central idea of the passage?',
            ['Black pepper has always been a cheap and easily available kitchen ingredient.',
              'European merchants invented spices and were the first ever to harvest them.',
              'Sailors avoided long voyages because the spice trade was already too crowded.',
              'The high cost of distant spices spurred voyages that eventually made spices common.'],
            3,
            ['The passage says spices were once nearly as valuable as silver.',
              'Merchants traded spices; they did not invent or first harvest them.',
              'The high prices drove sailors to seek new routes, not avoid voyages.',
              'Correct. The passage links costly, rare spices to voyages that made them ordinary.'],
            'The passage traces spices from costly rarity to abundance through new sea routes.'),
        'inference': (
            'It can reasonably be inferred that merchants spread tall tales about spices in order to',
            ['lower the prices that buyers were willing to pay',
              'keep competitors away from their profitable trade routes',
              'teach customers the correct way to cook with spices',
              'encourage as many new sailors as possible to enter the trade'],
            1,
            ["High prices, not lower ones, served the merchants' interest.",
              "Correct. The passage says the tales were meant 'to discourage rivals.'",
              'The tales were about harvesting, not cooking instruction.',
              'Tales discouraged rivals rather than recruiting newcomers.'],
            'The tales served to protect routes by discouraging competitors.'),
        'structure': (
            'The final sentence mainly serves to',
            ['give step-by-step directions for harvesting black pepper',
              'argue that the spice voyages should never have happened',
              'note an irony in which success undid the rarity it depended on',
              'introduce a new spice that had not been mentioned earlier'],
            2,
            ['No harvesting directions appear.',
              'The passage does not argue the voyages were a mistake.',
              'Correct. It highlights the irony that abundance dissolved the fortunes built on rarity.',
              'No new spice is introduced at the end.'],
            'The closing sentence delivers the irony of rarity undone by success.'),
        'wic': (
            'As used in the passage, the word “dissolved” most nearly means',
            ['melted into liquid',
              'broke a contract',
              'settled a dispute',
              'faded away'],
            3,
            ['No literal melting of fortunes occurs.',
              'No contract is being broken here.',
              'Settling a dispute is not the sense.',
              'Correct. The fortunes faded away as spices became common.'],
            "Fortunes that 'dissolved' faded away."),
        'evidence': (
            'Which detail best supports the claim that spices were once extremely valuable?',
            ['the statement that a handful of pepper could rival a handful of silver',
              'the statement that merchants guarded their trade routes jealously',
              'the statement that sea voyages redrew the map of the world',
              'the statement that spices grew only in distant lands'],
            0,
            ['Correct. Pepper rivaling silver directly shows its great value.',
              'Guarding routes shows protectiveness, not the value figure.',
              'Redrawing the map is an effect, not evidence of value.',
              'Distant origins explain scarcity, not value directly.'],
            'The pepper-rivaling-silver detail supports the value claim.'),
    },
    {
        "id": 'echo_bat', "title": 'Seeing With Sound',
        "text": (
            "A bat hunting in pitch darkness does not bump into things. It calls out, often at pitches too high for humans to hear, and listens for the echoes that bounce back. From the delay between call and echo, the bat judges how far away an object is; from subtle shifts in the returning sound, it can tell whether the object is moving toward it or away. A moth's fluttering wing returns a different echo than a still leaf. So precise is this sense that some bats can snatch an insect from the air in total darkness. The world the bat perceives is built entirely of sound, a picture painted with echoes."),
        'main_idea': (
            'Which choice best states the central idea of the passage?',
            ['Bats produce sounds that humans can easily hear during the night.',
              'Bats can detect only objects that are completely still, never moving ones.',
              'Bats perceive their surroundings in the dark by interpreting echoes of their own calls.',
              'Bats rely chiefly on their sharp eyesight to hunt insects after dark.'],
            2,
            ['The calls are often too high for humans to hear.',
              'Bats detect motion through shifts in the returning sound.',
              'Correct. The passage explains how bats build a sound-based picture from echoes.',
              'The passage describes hunting by sound, not eyesight.'],
            'The passage centers on echolocation as a sound-built perception of the world.'),
        'inference': (
            "It can reasonably be inferred that the delay between a bat's call and its echo tells the bat about an object's",
            ['color',
              'temperature',
              'weight',
              'distance'],
            3,
            ['Color is never linked to the echoes.',
              'Temperature is not mentioned.',
              'Weight is not part of what the echo reveals.',
              'Correct. The passage says the delay lets the bat judge how far away an object is.'],
            'The call-to-echo delay corresponds to distance.'),
        'structure': (
            "The example of the moth's wing versus a still leaf mainly serves to",
            ['illustrate how finely a bat can distinguish objects by echo',
              'prove that moths are the only prey that bats are able to catch',
              'explain why leaves make better food for bats than insects do',
              'list the steps a bat follows when building its nighttime roost'],
            0,
            ['Correct. The contrast shows the precision of echo-based perception.',
              'The passage does not limit bat prey to moths.',
              'Bats do not eat leaves; the leaf is a contrast object.',
              'No roost-building steps are given.'],
            'The moth-versus-leaf example demonstrates the precision of echolocation.'),
        'wic': (
            'As used in the passage, the word “snatch” most nearly means',
            ['glance briefly',
              'grab quickly',
              'complain sharply',
              'tear into pieces'],
            1,
            ['A brief glance does not fit the action described.',
              'Correct. The bat grabs an insect quickly from the air.',
              'No complaining is meant.',
              'Tearing into pieces is not the sense here.'],
            "To 'snatch an insect from the air' is to grab it quickly."),
        'evidence': (
            'Which detail best supports the claim that bats can sense whether an object is moving?',
            ['the statement that subtle shifts in the returning sound reveal motion toward or away',
              'the statement that bats call at pitches too high for humans to hear',
              'the statement that the bat judges distance from the delay of the echo',
              'the statement that the world the bat perceives is built entirely of sound'],
            0,
            ['Correct. Shifts in the returning sound directly indicate motion.',
              'The pitch of the call does not address motion sensing.',
              'Echo delay reveals distance, not motion direction.',
              "The 'built of sound' image is general, not motion-specific."],
            "Motion sensing is supported by the 'subtle shifts' detail."),
    },
    {
        "id": 'ledger_zero', "title": 'The Number That Was Nothing',
        "text": (
            'For much of history, there was no symbol for nothing. People counted sheep and coins easily enough, but the idea of writing down an empty amount seemed pointless, even unsettling. The breakthrough came when mathematicians treated zero not as the absence of a number but as a number in its own right, one that could be added, subtracted, and used to hold a place in larger figures. With zero, the difference between 5 and 50 could be written clearly, and long calculations grew far simpler. A concept that once felt like a riddle became the quiet hinge on which much of modern mathematics turns.'),
        'main_idea': (
            'Which choice best states the central idea of the passage?',
            ['Mathematicians decided that zero should be removed from written calculations.',
              'Treating zero as a true number transformed how people could write and calculate.',
              'Ancient people were unable to count sheep or coins without using zero.',
              'Zero was always understood as an ordinary number throughout all of history.'],
            1,
            ['Mathematicians embraced zero, rather than removing it.',
              'Correct. The passage shows how recognizing zero as a number reshaped writing and calculation.',
              'The passage says people counted sheep and coins easily without zero.',
              'The passage says zero was long absent and unsettling, not always understood.'],
            "The passage's point is that accepting zero as a number transformed mathematics."),
        'inference': (
            'It can reasonably be inferred that, before zero, writing large numbers clearly was',
            ['completely impossible in every case',
              'unaffected by the lack of a zero symbol',
              'more difficult than it became afterward',
              'easier than it became afterward'],
            2,
            ['People still wrote numbers before zero, so it was not impossible.',
              'The passage shows the lack of zero did affect clear writing.',
              'Correct. The passage says zero let differences like 5 and 50 be written clearly.',
              'The passage implies the opposite: zero made writing easier.'],
            'Without zero, distinguishing figures like 5 and 50 was harder.'),
        'structure': (
            'The passage develops its main idea primarily by',
            ['listing the names of the mathematicians who first studied zero',
              'providing a worked example of multiplying two large numbers',
              'comparing two competing symbols once used to represent zero',
              'contrasting the older discomfort with zero against its later usefulness'],
            3,
            ['No mathematicians are named.',
              'No worked multiplication example appears.',
              'No two zero symbols are compared.',
              'Correct. It sets the early unease about zero against its eventual power.'],
            'The structure contrasts old discomfort with later usefulness.'),
        'wic': (
            'As used in the passage, the word “hinge” most nearly means',
            ['a faint trace of a particular quality',
              'a crucial element on which something depends',
              'a metal joint that lets a door swing',
              'a sudden moment of doubt or hesitation'],
            1,
            ["The 'faint trace' sense (a hint) does not fit here.",
              'Correct. Zero is the crucial element on which modern math turns.',
              'The literal door-joint sense does not fit the abstract use.',
              'No doubt or hesitation is meant.'],
            "The 'quiet hinge on which math turns' is a crucial element it depends on."),
        'evidence': (
            'Which detail best supports the claim that zero made calculations easier?',
            ['the statement that an empty amount once seemed pointless to write',
              'the statement that zero once felt like a riddle to people',
              'the statement that long calculations grew far simpler once zero was used',
              'the statement that people counted sheep and coins easily enough'],
            2,
            ['An empty amount seeming pointless concerns the old attitude.',
              'Zero feeling like a riddle describes early confusion, not easier math.',
              "Correct. 'Long calculations grew far simpler' directly supports the claim.",
              'Counting sheep without zero does not show calculations got easier.'],
            "Easier calculation is supported by the 'far simpler' detail."),
    },
    {
        "id": 'salt_marsh', "title": 'The Quiet Buffer',
        "text": (
            'Where the land meets the sea, a salt marsh can look like wasteland: flat, muddy, and crossed by winding channels. Yet this drab landscape does remarkable work. Its dense grasses slow incoming waves, blunting the force of storms before they reach homes inland. The same grasses trap sediment, letting the marsh build itself upward as the sea slowly rises. Beneath the mud, roots store carbon that might otherwise warm the air. For years, marshes were drained and filled without much thought. Only later did people recognize that the unglamorous marsh had been protecting them all along, asking nothing in return.'),
        'main_idea': (
            'Which choice best states the central idea of the passage?',
            ['Salt marshes are beautiful landscapes that people have always admired greatly.',
              'Draining marshes is the most effective way to defend homes from storms.',
              'Salt marshes release large amounts of stored carbon into the warming air.',
              'Plain-looking salt marshes provide valuable protection that was long overlooked.'],
            3,
            ['The passage calls the marsh drab and once-overlooked, not always admired.',
              'Draining marshes removed protection rather than providing it.',
              'The roots store carbon rather than releasing it.',
              'Correct. The passage shows the drab marsh doing protective work long unappreciated.'],
            'The passage reveals the overlooked marsh as a valuable natural protector.'),
        'inference': (
            'It can reasonably be inferred that draining and filling marshes most likely left coastal communities',
            ['more exposed to the force of storms',
              'better protected from rising seas',
              'wealthier from the carbon they stored',
              'surrounded by thicker marsh grasses'],
            0,
            ['Correct. Since marshes blunt storms, removing them would increase exposure.',
              'Draining removed the buffer, reducing protection from the sea.',
              'Draining released, rather than profited from, stored carbon.',
              'Filling marshes destroys grasses rather than thickening them.'],
            'Removing the marsh buffer would leave communities more exposed to storms.'),
        'structure': (
            'Which choice best describes how the passage is organized?',
            ['It narrates the personal story of one person who lived by a marsh.',
              'It gives instructions for restoring a marsh that has been drained.',
              "It overturns a first impression by detailing the marsh's hidden benefits.",
              'It compares two different marshes located on opposite coasts.'],
            2,
            ['No personal story is told.',
              'No restoration instructions are given.',
              'Correct. It begins with the marsh looking like wasteland, then reveals its value.',
              'No two marshes are compared.'],
            "The passage moves from a dismissive first impression to the marsh's real worth."),
        'wic': (
            'As used in the passage, the word “blunting” most nearly means',
            ['speaking too plainly',
              'making dull in color',
              'cutting in half',
              'reducing the force of'],
            3,
            ["The 'speaking plainly' sense does not fit.",
              'Color dullness is not the sense here.',
              'Cutting in half is not what the grasses do to waves.',
              'Correct. The grasses reduce the force of storms.'],
            "To be 'blunting the force' is to reduce that force."),
        'evidence': (
            'Which detail best supports the claim that marshes can keep pace with rising seas?',
            ['the statement that the grasses trap sediment, letting the marsh build itself upward',
              'the statement that the marsh can look like flat, muddy wasteland',
              'the statement that roots beneath the mud store carbon',
              'the statement that marshes were once drained and filled without much thought'],
            0,
            ['Correct. Trapping sediment to build upward directly shows the marsh keeping pace with the sea.',
              "The marsh's plain appearance does not address rising seas.",
              'Carbon storage is a separate benefit, not pace with the sea.',
              'Past draining concerns history, not keeping pace.'],
            'Keeping pace with the sea is supported by the sediment-trapping detail.'),
    },
    {
        "id": 'letter_home', "title": 'The Unsent Letter',
        "text": (
            'Tomas wrote the letter three times before he stopped trying to send it. In the first version he was cheerful, listing the small triumphs of his new city as if homesickness were a thing he had outgrown. In the second he was honest, and the page filled with everything he missed until it embarrassed him. The third version said almost nothing at all. He kept that one folded in a drawer. Months later he found it again and realized the words he could not send had still done their work: writing them had let him admit, if only to himself, how far from home he truly felt.'),
        'main_idea': (
            'Which choice best states the main idea of the passage?',
            ['Tomas writes the letters mainly to impress the friends in his new city.',
              'Writing an unsent letter helps Tomas privately acknowledge his homesickness.',
              'Tomas mails the most honest of his three letters to his family at last.',
              'Tomas decides he no longer misses his hometown now that he has moved.'],
            1,
            ['The letters are addressed home, not aimed at impressing new friends.',
              'Correct. The closing lines show the unsent writing let him admit his homesickness.',
              'He keeps the letter folded in a drawer rather than mailing it.',
              'The passage shows he does miss home, not that he stopped.'],
            'The narrative resolves on writing as a way to admit feelings to himself.'),
        'inference': (
            'It can reasonably be inferred that the first version of the letter was',
            ['more cheerful than Tomas actually felt',
              'an honest account of his deep homesickness',
              'the version he ultimately decided to send',
              'written to confess how far from home he felt'],
            0,
            ["Correct. He was cheerful 'as if homesickness were a thing he had outgrown,' though he had not.",
              'The honest account was the second version, not the first.',
              'He sent none of the versions.',
              'Confessing his homesickness describes the later realization, not the cheerful first draft.'],
            'The first draft put on cheerfulness he did not truly feel.'),
        'structure': (
            'The passage is structured mainly as',
            ['a comparison of two different cities Tomas has lived in',
              'a sequence of three drafts leading to a final realization',
              'a back-and-forth argument between Tomas and a friend',
              'a numbered list of tips for writing a letter home'],
            1,
            ['Two cities are not compared in detail.',
              "Correct. It moves through the three versions to Tomas's closing insight.",
              'There is no argument between characters.',
              'No tips are listed.'],
            'The arc runs through three drafts to a final realization.'),
        'wic': (
            'As used in the passage, the word “triumphs” most nearly means',
            ['loud noises',
              'military victories',
              'successes',
              'celebrations with crowds'],
            2,
            ['No loud noises are meant.',
              "The literal military sense does not fit 'small' personal wins.",
              'Correct. He lists his small successes in the new city.',
              'No crowd celebration is described.'],
            "His 'small triumphs' are small successes."),
        'evidence': (
            'Which detail best supports the idea that writing helped Tomas understand his own feelings?',
            ['the detail that the first version listed the small triumphs of his new city',
              'the detail that he wrote the letter three times before stopping',
              'the detail that he kept the third version folded in a drawer',
              'the detail that writing the words let him admit how far from home he felt'],
            3,
            ['The cheerful list hid, rather than revealed, his feelings.',
              'Writing it three times shows effort, not the self-understanding itself.',
              'Keeping the letter in a drawer does not by itself show understanding.',
              'Correct. This directly states that the writing let him admit his feelings.'],
            'Self-understanding is shown by the line about admitting how far from home he felt.'),
    },
    {
        "id": 'vote_paper', "title": 'The Secret Ballot',
        "text": (
            'It is easy to assume voting has always been private, but for a long time it was not. In many places people voted aloud or by a show of hands, in full view of employers, landlords, and neighbors. That openness invited pressure: a worker might think twice before voting against a boss who could see the choice. Reformers pushed for a printed ballot, marked alone and dropped in a box, so that no one need fear retaliation for an honest vote. The change seemed minor, a mere matter of paper, yet it shifted real power toward the ordinary voter, who could now decide without an audience.'),
        'main_idea': (
            'Which choice best states the central idea of the passage?',
            ['Reformers opposed the printed ballot as an unnecessary change.',
              'The secret ballot freed voters to choose without fear of pressure or retaliation.',
              'Voting has always been conducted privately throughout recorded history.',
              'Public voting by show of hands gave ordinary workers the most power.'],
            1,
            ['Reformers pushed for the printed ballot, not against it.',
              'Correct. The passage explains how private ballots protected voters from pressure.',
              'The passage says voting was long public, not always private.',
              'Public voting invited pressure on workers, reducing their power.'],
            "The passage's point is that the secret ballot protected the ordinary voter's free choice."),
        'inference': (
            'It can reasonably be inferred that public voting was a problem chiefly because it',
            ['required voters to travel long distances to vote',
              'prevented neighbors from ever discussing politics',
              'let powerful people see and punish how others voted',
              'made the counting of votes slow and unreliable'],
            2,
            ['Travel distance is never mentioned.',
              'Public voting did not stop political discussion.',
              'Correct. The passage says open voting invited pressure and fear of retaliation.',
              'Vote-counting speed is not discussed.'],
            'The danger of public voting was exposure to pressure and punishment.'),
        'structure': (
            "The author calls the change 'a mere matter of paper' mainly to",
            ['argue that the reform was, in the end, not worth the trouble',
              'explain the precise steps for printing an official ballot',
              'suggest that paper ballots were too costly to produce widely',
              'set up a contrast with the large effect the change actually had'],
            3,
            ['The passage treats the reform as important, not pointless.',
              'No printing steps are given.',
              'Cost of ballots is not discussed.',
              'Correct. The phrase downplays the change to highlight its surprisingly large effect.'],
            "The 'mere paper' phrase contrasts a small change with a large effect."),
        'wic': (
            'As used in the passage, the word “pressure” most nearly means',
            ['coercive influence',
              'physical force on a surface',
              'a feeling of hurry',
              'air weight in a tire'],
            0,
            ['Correct. Voters faced coercive influence from those who could see their vote.',
              'No physical force on a surface is meant.',
              'A sense of hurry does not fit the context.',
              'The tire-pressure sense is unrelated.'],
            "Here 'pressure' means coercive influence on voters."),
        'evidence': (
            'Which detail best supports the claim that public voting could intimidate voters?',
            ['the statement that the change shifted power toward the ordinary voter',
              'the statement that it is easy to assume voting has always been private',
              'the statement that a worker might think twice before voting against a watching boss',
              'the statement that reformers pushed for a printed ballot dropped in a box'],
            2,
            ['The power shift is the effect of reform, not the intimidation itself.',
              'The opening assumption does not show intimidation.',
              'Correct. The hesitant worker example directly shows intimidation under public voting.',
              "The reformers' push is the response, not evidence of intimidation."],
            'Intimidation is supported by the watching-boss example.'),
    },
    {
        "id": 'ice_core', "title": 'Bubbles of Old Air',
        "text": (
            "Each winter's snowfall on a polar ice sheet does not entirely melt; it packs down, traps tiny pockets of air, and slowly turns to ice. Layer settles on layer, year after year, so that drilling deep into the ice is a way of drilling back through time. Trapped in those bubbles is a sample of the very atmosphere that existed when the snow fell, including the gases it carried. By analyzing cores pulled from kilometers down, researchers can compare today's air with the air of tens of thousands of years ago. The ice keeps no diary of dates, yet its layers, counted carefully, let scientists assign an age to each whisper of ancient air."),
        'main_idea': (
            'Which choice best states the central idea of the passage?',
            ["Polar snow melts completely each summer before the next winter's snowfall.",
              'Ice cores are useful only for measuring the present-day composition of air.',
              'Drilling into ice destroys the trapped bubbles before they can be studied.',
              'Ice cores preserve ancient air in layered bubbles that record past atmospheres.'],
            3,
            ['The passage says winter snow does not entirely melt.',
              'Cores let researchers study ancient, not just present, air.',
              'The passage describes analyzing the bubbles, not destroying them.',
              'Correct. The passage explains how layered ice traps and dates ancient air.'],
            'The passage centers on ice cores as a layered record of past atmospheres.'),
        'inference': (
            'It can reasonably be inferred that deeper layers of an ice sheet generally contain air that is',
            ['older than the air in shallower layers',
              'younger than the air in shallower layers',
              'free of any trapped gases at all',
              "identical in age to today's atmosphere"],
            0,
            ['Correct. Layers settle over time, so deeper ice formed earlier and traps older air.',
              'Deeper layers are older, not younger.',
              'The passage says bubbles trap the gases the air carried.',
              'Deeper air is from the distant past, not today.'],
            'Because layers accumulate over time, deeper air is older.'),
        'structure': (
            'The passage is organized mainly by',
            ['arguing that polar drilling should be banned to protect the ice',
              'explaining how the ice forms, then how it is read for past air',
              'comparing two rival teams of scientists drilling the same ice',
              'listing the safety steps a driller must follow on the ice'],
            1,
            ['No banning argument appears.',
              'Correct. It first describes how layered ice forms, then how cores reveal old air.',
              'No two teams are compared.',
              'No safety steps are listed.'],
            'The structure moves from ice formation to reading the record.'),
        'wic': (
            'As used in the passage, the word “packs” most nearly means',
            ['presses tightly together',
              'fills a suitcase',
              "carries on one's back",
              'forms an animal group'],
            0,
            ['Correct. The snow presses tightly together as it turns to ice.',
              'No suitcase is involved.',
              "Carrying on one's back is not the sense.",
              'An animal group is not meant here.'],
            "Snow that 'packs down' presses tightly together."),
        'evidence': (
            'Which detail best supports the claim that ice cores capture air from the distant past?',
            ['the statement that drilling deep is a way of drilling back through time',
              'the statement that the bubbles hold the very atmosphere that existed when the snow fell',
              "the statement that each winter's snowfall does not entirely melt",
              'the statement that the ice keeps no diary of dates'],
            1,
            ["The 'drilling back through time' image is a metaphor, less direct than the bubble detail.",
              'Correct. The bubbles holding the atmosphere of when the snow fell directly captures past air.',
              'Snow not melting explains how layers form, not the captured air.',
              "Keeping 'no diary of dates' concerns dating, not capturing old air."],
            'Capturing past air is supported by the trapped-atmosphere detail.'),
    },
    {
        "id": 'market_day', "title": 'The Stall That Listened',
        "text": (
            "Every Saturday, Mr. Owusu set out the same vegetables on the same table, and for years his stall was just one among many. What set him apart, his daughter noticed, was not his prices but his memory. He recalled which customer's child disliked onions, who was cooking for a crowd that weekend, who had been ill and needed something gentle. He would set aside a perfect tomato for one regular and toss an extra handful of beans to another. People did not return only for the produce; they returned because, at his stall, they were known. When he finally retired, the market felt larger and lonelier, though not a single other stall had closed."),
        'main_idea': (
            'Which choice best states the main idea of the passage?',
            ['The market declined because several stalls closed at around the same time.',
              "Mr. Owusu's daughter took over the stall and ran it just as he had.",
              "Mr. Owusu's attentiveness to customers, not his produce, made his stall special.",
              "Mr. Owusu succeeded mainly because his vegetables cost less than his rivals' did."],
            2,
            ['The passage notes that not a single other stall had closed.',
              'The daughter notices his gift; the passage does not say she took over.',
              'Correct. The passage stresses that customers returned because he knew and remembered them.',
              'The passage says it was not his prices that set him apart.'],
            "The passage's point is that personal attentiveness, not produce, drew customers back."),
        'inference': (
            "It can reasonably be inferred that customers valued Mr. Owusu's stall chiefly because they felt",
            ['that his prices were the lowest available',
              'rushed through their purchases quickly',
              'uncertain about the quality of his produce',
              'personally recognized and cared for'],
            3,
            ['The passage explicitly says it was not his prices.',
              'Nothing suggests customers were rushed.',
              'His setting aside perfect produce implies quality, not doubt.',
              "Correct. The passage says they returned because, at his stall, 'they were known.'"],
            'Customers valued feeling known and cared for.'),
        'structure': (
            'The final sentence mainly serves to',
            ['list the kinds of vegetables that the market still sold',
              'show the personal loss his absence left despite no stalls closing',
              'explain the exact reasons that he chose to retire when he did',
              'introduce a rival vendor who took over his former spot'],
            1,
            ['No list of remaining vegetables appears.',
              'Correct. It conveys the emptiness his absence created though the market was physically unchanged.',
              'His reasons for retiring are not given.',
              'No rival vendor is introduced.'],
            'The closing line underscores the personal loss his retirement caused.'),
        'wic': (
            'As used in the passage, the word “regular” most nearly means',
            ['a normal size of product',
              'a steady rhythm',
              'a frequent customer',
              'an ordinary soldier'],
            2,
            ['A product size is not meant here.',
              'A steady rhythm is unrelated to the context.',
              'Correct. He set aside a tomato for a frequent customer.',
              'The soldier sense does not fit a market stall.'],
            "Here 'a regular' is a frequent customer."),
        'evidence': (
            'Which detail best supports the idea that Mr. Owusu paid close attention to individual customers?',
            ['the detail that he set out the same vegetables every Saturday',
              'the detail that his stall was, for years, just one among many',
              'the detail that the market felt larger after he retired',
              "the detail that he recalled which customer's child disliked onions"],
            3,
            ['Setting out the same vegetables shows routine, not personal attention.',
              'Being one stall among many does not show attentiveness.',
              'The market feeling larger is the effect of his absence, not his attention.',
              "Correct. Remembering a specific child's dislike shows close attention to individuals."],
            "Close personal attention is shown by his recalling the child's dislike of onions."),
    },
    {
        "id": 'river_delta', "title": 'Land Made of Mud',
        "text": (
            'A great river carries more than water; it carries soil, scoured from distant hills and ground into fine particles. Where the river finally slows and meets the sea, it can no longer hold this load, and the sediment settles out, building flat new land called a delta. Over centuries a delta can grow seaward, fanning into a maze of channels and islands. But the process depends on a steady supply of mud. When dams upstream trap that sediment, the delta is starved; waves carry off more land than the river replaces, and the coastline begins to retreat. What looks like permanent ground is, in truth, a balance constantly being rebuilt.'),
        'main_idea': (
            'Which choice best states the central idea of the passage?',
            ['A delta is built by river sediment and shrinks when that supply is cut off.',
              'Rivers carry only clear water and never any soil from distant hills.',
              'Dams reliably help deltas grow larger by holding back excess water.',
              'Deltas are permanent landforms that never change once they have formed.'],
            0,
            ['Correct. The passage explains deltas as sediment-built land that erodes when the supply is trapped.',
              'The passage says rivers carry soil, not only water.',
              'Dams starve deltas by trapping sediment, not helping them grow.',
              'The passage stresses deltas are a constantly rebuilt balance, not permanent.'],
            'The passage shows deltas as sediment-dependent land that retreats when starved of mud.'),
        'inference': (
            'It can reasonably be inferred that a delta downstream of a large new dam would most likely',
            ['stop receiving any river water at all',
              'remain exactly the same size forever',
              'lose land to the sea over time',
              'gain land more quickly than before'],
            2,
            ['The dam traps sediment, not all the water.',
              'The passage says a starved delta retreats, not stays the same.',
              'Correct. Dams trap sediment, starving the delta so waves carry off more land.',
              'Reduced sediment shrinks the delta rather than speeding growth.'],
            'A sediment-starved delta would lose land to the sea.'),
        'structure': (
            'The passage is organized mainly by',
            ['comparing two famous deltas on different continents in detail',
              'listing the steps engineers follow when designing a river dam',
              'narrating the journey of one boat down a river to the sea',
              'explaining how a delta forms, then how losing sediment reverses the process'],
            3,
            ['No two deltas are compared in detail.',
              'No dam-design steps are given.',
              'No boat journey is narrated.',
              'Correct. It first describes delta building, then sediment loss and retreat.'],
            'The structure moves from delta formation to the reversal caused by lost sediment.'),
        'wic': (
            'As used in the passage, the word “starved” most nearly means',
            ['deprived of a needed supply',
              'made extremely hungry',
              'frozen by cold',
              'frightened into stillness'],
            0,
            ['Correct. The delta is deprived of the sediment supply it needs.',
              'The literal hunger sense does not apply to a landform.',
              'Cold and freezing are not the sense here.',
              'Fear is unrelated to the context.'],
            "A delta that is 'starved' is deprived of its needed sediment supply."),
        'evidence': (
            'Which detail best supports the claim that a delta depends on continuing sediment delivery?',
            ['the statement that the river slows where it finally meets the sea',
              'the statement that when dams trap sediment, the delta is starved and the coast retreats',
              'the statement that a river carries soil scoured from distant hills',
              'the statement that a delta can fan into a maze of channels and islands'],
            1,
            ['The river slowing explains why sediment settles, not the ongoing dependence.',
              "Correct. The dam-and-retreat detail directly shows the delta's dependence on sediment supply.",
              'Carrying soil explains the source, not the dependence over time.',
              'The maze of channels describes shape, not the supply dependence.'],
            'Dependence on sediment is supported by the dam-starvation detail.'),
    },
    {
        "id": 'clock_towns', "title": 'When Noon Moved',
        "text": (
            "Before railroads, every town kept its own time, set by the sun overhead at noon. A traveler crossing the country adjusted a watch town by town, and no one minded a few minutes' difference. Railroads made the patchwork intolerable. Trains ran on schedules, and a schedule means nothing if each station defines noon differently; a missed connection could be a matter of life and death. So the railways carved the land into broad zones, each agreeing to share a single time. People grumbled at first about clocks that no longer matched the sun, but the convenience won out. The hour on the wall had become a public agreement rather than a private reading of the sky."),
        'main_idea': (
            'Which choice best states the central idea of the passage?',
            ['Railroads drove the shift from local sun time to shared, standardized time zones.',
              'Towns before railroads all happened to keep exactly the same time as one another.',
              'Standard time zones existed long before any railroads were ever built.',
              'People universally welcomed standard time the moment it was first proposed.'],
            0,
            ['Correct. The passage explains how railway schedules forced a move to shared time zones.',
              'The passage says each town kept its own time, not the same time.',
              'Time zones came in response to railroads, not before them.',
              'The passage says people grumbled at first before accepting the change.'],
            "The passage's point is that railroads pushed local time into standardized zones."),
        'inference': (
            'It can reasonably be inferred that railroads made local sun time a problem because trains',
            ['were unable to operate during the daylight hours at all',
              'depended on schedules that required everyone to agree on the time',
              'could not run unless every town abandoned the use of clocks',
              'traveled too slowly for any timetable to matter to passengers'],
            1,
            ['Nothing suggests trains could not run in daylight.',
              'Correct. The passage says a schedule means nothing if each station defines noon differently.',
              'Standard time required shared clocks, not abandoning them.',
              'The passage stresses schedules mattered greatly, not that trains were slow.'],
            'Schedules required a shared definition of time, which local sun time prevented.'),
        'structure': (
            'The passage develops its main idea primarily by',
            ['listing the steps for setting a watch by the noon sun',
              'tracing the biography of the inventor of the clock',
              'showing a problem and the standardized solution it produced',
              "comparing two competing railway companies' timetables"],
            2,
            ['No watch-setting steps are listed.',
              "No inventor's biography is traced.",
              'Correct. It presents the scheduling problem and the time-zone solution.',
              'No two companies are compared.'],
            'The structure presents a problem followed by its standardized solution.'),
        'wic': (
            'As used in the passage, the word “carved” most nearly means',
            ['cut a roast of meat',
              'sculpted from wood',
              'wore down by erosion',
              'divided into parts'],
            3,
            ['No meat is being cut.',
              'No wood sculpting is meant.',
              'Erosion is not the sense here.',
              'Correct. The railways divided the land into broad zones.'],
            "To 'carve the land into zones' is to divide it into parts."),
        'evidence': (
            'Which detail best supports the claim that inconsistent local time could be dangerous?',
            ['the statement that a traveler adjusted a watch town by town',
              'the statement that a missed connection could be a matter of life and death',
              'the statement that each town set its time by the sun overhead at noon',
              'the statement that people grumbled about clocks no longer matching the sun'],
            1,
            ['Adjusting a watch shows inconvenience, not danger.',
              "Correct. 'A matter of life and death' directly shows the danger of inconsistent time.",
              'Setting time by the sun describes the old method, not the danger.',
              'Grumbling about clocks concerns reaction, not danger.'],
            "The danger is supported by the 'life and death' detail."),
    },
    {
        "id": 'seed_wind', "title": 'Travelers Without Legs',
        "text": (
            "A plant cannot walk, yet its seeds must somehow leave the shadow of the parent and find open ground. Evolution has answered this need with a surprising range of tricks. Some seeds grow papery wings and spin away on the wind like tiny helicopters. Others wear hooks that snag the fur of passing animals, hitching a ride for miles. Still others hide inside sweet fruit, counting on an animal to eat them and carry them off, depositing them far away. Each method is a kind of bargain struck with the world around the plant. The seed that travels farthest is often the one with the best chance to grow where the parent's shade cannot reach."),
        'main_idea': (
            'Which choice best states the central idea of the passage?',
            ['Seeds always grow best directly beneath the shade of the parent plant.',
              'Wind is the only means by which any plant can spread its seeds.',
              'Plants have evolved varied methods to disperse their seeds away from the parent.',
              'Plants are able to uproot themselves and walk to find better ground.'],
            2,
            ["The passage says seeds need to leave the parent's shadow.",
              'The passage describes wind, hooks, and fruit, not wind alone.',
              'Correct. The passage surveys several strategies plants use to move their seeds.',
              'The passage opens by noting a plant cannot walk.'],
            "The passage's focus is the variety of seed-dispersal strategies."),
        'inference': (
            'It can reasonably be inferred that seeds wear hooks in order to',
            ['make the seeds heavier so they fall straight down',
              'protect the seeds from being eaten by any animal',
              'help the seeds spin like helicopters in the wind',
              'catch onto animals that carry them to new places'],
            3,
            ['Hooks aid travel, not added weight to fall straight down.',
              'Hooks help seeds catch a ride, not avoid being eaten.',
              'Spinning like a helicopter describes winged seeds, not hooked ones.',
              'Correct. The passage says hooked seeds snag passing animals and hitch a ride.'],
            'Hooks let seeds catch onto animals for transport.'),
        'structure': (
            'The passage is organized mainly by',
            ['stating a problem, then listing several solutions plants have evolved',
              'comparing two specific plant species side by side in detail',
              'giving instructions for planting seeds at the right depth',
              'arguing that wind dispersal should be studied above all others'],
            0,
            ['Correct. It poses the dispersal problem, then lists wind, hook, and fruit solutions.',
              'No two species are compared in detail.',
              'No planting instructions are given.',
              'The passage does not argue to prioritize one method.'],
            'The structure is a problem followed by a list of evolved solutions.'),
        'wic': (
            'As used in the passage, the word “snag” most nearly means',
            ['a small hidden problem',
              'tear a hole in cloth',
              'catch on',
              'obtain a bargain'],
            2,
            ["The 'hidden problem' noun sense is not used here.",
              'Tearing cloth is not the action described.',
              'Correct. The hooked seeds catch on the fur of passing animals.',
              "The 'get a bargain' sense does not fit."],
            "Here 'snag the fur' means catch on it."),
        'evidence': (
            'Which detail best supports the claim that some seeds rely on animals eating them?',
            ['the statement that some seeds grow papery wings and spin on the wind',
              'the statement that some seeds wear hooks that snag passing fur',
              'the statement that a plant cannot walk to find open ground',
              'the statement that some seeds hide in sweet fruit so an animal eats and carries them off'],
            3,
            ['Winged seeds rely on wind, not on being eaten.',
              'Hooked seeds rely on fur, not on being eaten.',
              'The opening notes a plant cannot walk, unrelated to being eaten.',
              'Correct. Hiding in fruit to be eaten and carried directly supports the claim.'],
            'Reliance on being eaten is supported by the sweet-fruit detail.'),
    },
    {
        "id": 'almanac_farm', "title": 'Reading the Weather Before Radio',
        "text": (
            "Long before satellites mapped storms from orbit, farmers learned to read the sky and the land for signs of coming weather. A ring of haze around the moon, the smell of soil before rain, the behavior of swallows flying low: such clues were gathered into almanacs and passed down through families. Much of this folk knowledge was unreliable, mixing keen observation with superstition. Yet some of it held real wisdom, since the conditions that produce a hazy moon truly can precede rain. Modern forecasting has not so much replaced this older watching as absorbed its best parts, trading the rooster's crow for the radar's sweep."),
        'main_idea': (
            'Which choice best states the central idea of the passage?',
            ['Folk weather signs mixed superstition with genuine insight that modern forecasting absorbed.',
              'Folk weather knowledge was entirely accurate and never mistaken in any case.',
              'Modern forecasting completely discarded every part of older weather watching.',
              'Farmers ignored the sky and the land when trying to predict the weather.'],
            0,
            ['Correct. The passage says folk signs blended superstition and real wisdom, the best of which forecasting absorbed.',
              'The passage says much folk knowledge was unreliable.',
              'The passage says modern forecasting absorbed, not discarded, the best parts.',
              'The passage shows farmers read the sky and land closely.'],
            'The passage balances the flaws and genuine insight of folk weather signs.'),
        'inference': (
            'It can reasonably be inferred that the author regards folk weather signs as',
            ['purely superstition with no basis in real conditions',
              'a mix of useful observation and unreliable belief',
              'entirely useless and worth completely ignoring',
              'more accurate than any modern forecasting method'],
            1,
            ['Some signs, like the hazy moon, reflect real conditions.',
              'Correct. The passage says folk knowledge mixed keen observation with superstition.',
              'The passage credits some folk signs with real wisdom.',
              'The passage says forecasting absorbed the best parts, implying it is reliable.'],
            'The author views folk signs as a blend of insight and superstition.'),
        'structure': (
            "The phrase 'trading the rooster's crow for the radar's sweep' mainly serves to",
            ['capture how modern tools replaced older signs while serving the same goal',
              'argue that roosters predict weather better than radar does',
              'list the equipment a modern weather station requires',
              'explain how radar machines are built and maintained'],
            0,
            ['Correct. The phrase contrasts old and new tools that pursue the same forecasting aim.',
              'The passage does not claim roosters beat radar.',
              'The phrase is not a list of station equipment.',
              'Radar construction is not explained.'],
            'The image expresses the shift from old signs to modern tools serving the same purpose.'),
        'wic': (
            'As used in the passage, the word “absorbed” most nearly means',
            ['softened a heavy blow',
              'took in and incorporated',
              'soaked up a spilled liquid',
              "fully occupied one's attention"],
            1,
            ["The 'cushioned an impact' sense does not fit here.",
              'Correct. Modern forecasting took in and incorporated the best of the old signs.',
              'No literal liquid is soaked up.',
              "The 'held attention' sense does not fit the context."],
            "Forecasting 'absorbed' the best parts by taking them in and incorporating them."),
        'evidence': (
            'Which detail best supports the claim that some folk weather signs had real value?',
            ['the statement that much of the folk knowledge mixed in superstition',
              'the statement that satellites now map storms from orbit',
              'the statement that the conditions producing a hazy moon truly can precede rain',
              'the statement that such clues were gathered into almanacs and passed down'],
            2,
            ['The superstition detail shows the unreliable side, not the value.',
              'Satellite mapping describes modern tools, not folk-sign value.',
              'Correct. The hazy-moon-precedes-rain detail shows a folk sign with a real basis.',
              'Gathering clues into almanacs concerns how they spread, not their accuracy.'],
            'Real value is supported by the hazy-moon-precedes-rain detail.'),
    },
    {
        "id": 'kelp_forest', "title": 'Forests Beneath the Waves',
        "text": (
            'Off some cool, rocky coasts grow forests that no hiker will ever walk through. Giant kelp, anchored to the seafloor, can stretch dozens of meters toward the surface, swaying in the current like trees in wind. These kelp forests shelter fish, snails, and otters, much as a woodland shelters birds and deer. The kelp grows astonishingly fast, sometimes half a meter in a single day, drinking sunlight near the surface. But the forest is fragile. Where otters vanish, sea urchins multiply and graze the kelp down to bare rock, leaving a barren the divers call an urchin desert. A single missing animal can unmake a whole forest.'),
        'main_idea': (
            'Which choice best states the central idea of the passage?',
            ['Giant kelp grows so slowly that it can take many years to reach the surface.',
              'Sea otters are harmful pests that destroy the kelp forests they live in.',
              'Kelp forests are found mainly in warm, sandy waters near tropical beaches.',
              'Kelp forests are rich but fragile habitats that depend on a balance of species.'],
            3,
            ['The passage says kelp grows astonishingly fast, not slowly.',
              'Otters protect the kelp; their loss lets urchins destroy it.',
              'The passage places these forests off cool, rocky coasts.',
              'Correct. The passage presents kelp forests as rich habitats whose health rests on species balance.'],
            'The passage frames kelp forests as productive yet fragile, balanced ecosystems.'),
        'inference': (
            'It can reasonably be inferred that sea otters help kelp forests by',
            ['slowing the rapid growth of the kelp near the surface',
              'keeping the population of kelp-grazing urchins in check',
              'anchoring the giant kelp firmly to the rocky seafloor',
              'providing the sunlight that the growing kelp needs'],
            1,
            ['Otters do not slow kelp growth; their loss harms the kelp.',
              'Correct. When otters vanish, urchins multiply and graze the kelp down, so otters limit urchins.',
              'The kelp anchors itself; otters do not anchor it.',
              'Sunlight comes from the sun, not from otters.'],
            'Otters help by controlling the urchins that would otherwise destroy the kelp.'),
        'structure': (
            'The passage develops its main idea primarily by',
            ['listing the steps a diver takes to explore a kelp forest safely',
              'tracing the life of a single sea otter from birth to old age',
              "describing the forest's richness, then showing how easily it can collapse",
              'comparing two different species of kelp growing side by side'],
            2,
            ['No diving steps are listed.',
              "No otter's life story is traced.",
              'Correct. It first portrays the thriving forest, then the collapse into an urchin desert.',
              'No two kelp species are compared.'],
            "The structure moves from the forest's richness to its fragility."),
        'wic': (
            'As used in the passage, the word “graze” most nearly means',
            ['touch lightly in passing',
              'scrape the skin',
              'look over quickly',
              'feed on growing plants'],
            3,
            ["The 'brush against' sense does not fit the urchins eating kelp.",
              'Scraping skin is not the sense here.',
              "Glancing over quickly is unrelated to the urchins' action.",
              'Correct. The urchins feed on the growing kelp.'],
            "When urchins 'graze the kelp,' they feed on it."),
        'evidence': (
            'Which detail best supports the claim that a kelp forest can collapse quickly?',
            ['the statement that without otters, urchins multiply and graze the kelp to bare rock',
              'the statement that giant kelp can stretch dozens of meters toward the surface',
              'the statement that kelp forests shelter fish, snails, and otters',
              'the statement that the kelp can grow half a meter in a single day'],
            0,
            ['Correct. Urchins grazing the kelp to bare rock directly shows a collapse.',
              "The kelp's height describes its size, not a collapse.",
              'Sheltering animals describes richness, not collapse.',
              'Fast growth describes vigor, not collapse.'],
            'Collapse is supported by the urchins-graze-to-bare-rock detail.'),
    },
]


# Paired passages for cross-text connections. Each: two short texts that share a
# topic but differ in stance, plus two cross-text questions.
PAIRED2 = [
    {
        "id": 'uniforms',
        "text_a": ('School uniforms, the author argues, ease the daily pressure of choosing clothes and blur the visible signs of wealth between students. A common dress, the text says, lets young people focus on learning rather than appearance.'),
        "text_b": ('Requiring uniforms, this author counters, strips students of a harmless way to express who they are and rarely changes how they behave. The money families spend on required outfits, the text notes, could be better used elsewhere.'),
        "questions": [
            ('Based on the texts, the two authors most clearly disagree about whether',
             ['clothing of some kind is worn by students inside the classroom',
               'families are ever asked to purchase any items for school',
               'requiring school uniforms does more good than harm for students',
               'students attend school buildings during the academic year at all'],
             2,
             ['Both accept that students wear clothing.',
               'Both accept families buy school items.',
               "Correct. Text 1 praises uniforms' benefits; Text 2 sees them as costly and stifling.",
               'Both assume students attend school.'],
             'The disagreement is whether uniforms are, on balance, beneficial.'),
            ("How would the author of Text 2 most likely respond to Text 1's point that uniforms let students focus on learning?",
             ['by agreeing fully that uniforms should be required everywhere',
               'by claiming that students cannot learn anything while in uniform',
               'by insisting that families enjoy the expense of buying uniforms',
               'by questioning that effect and stressing the loss of self-expression'],
             3,
             ['Text 2 opposes, rather than supports, required uniforms.',
               'Text 2 does not claim uniforms make learning impossible.',
               'Text 2 calls the required expense a burden, not a pleasure.',
               'Correct. Text 2 doubts uniforms change behavior and emphasizes lost self-expression.'],
             'Text 2 would dispute the focus benefit and highlight the cost to self-expression.'),
        ],
    },
    {
        "id": 'self_drive',
        "text_a": ('Self-driving cars, the author predicts, will sharply cut crashes, since most accidents trace to human error such as distraction or fatigue. Machines, the text says, do not text, tire, or drink.'),
        "text_b": ('Handing driving to software, this author warns, raises hard questions software cannot easily answer, from split-second moral choices to who is at fault in a crash. Trust, the text argues, must be earned slowly.'),
        "questions": [
            ("Based on the texts, the author of Text 2 would most likely respond to Text 1's optimism by",
             ['raising unresolved questions of responsibility and judgment',
               'agreeing that the technology has no remaining drawbacks at all',
               'denying that human error causes any traffic crashes whatsoever',
               'arguing that human drivers never grow distracted or fatigued'],
             0,
             ['Correct. Text 2 stresses unsettled moral and liability questions.',
               'Text 2 raises drawbacks rather than dismissing them.',
               'Text 2 does not deny human error causes crashes.',
               'Text 2 does not claim humans are never distracted.'],
             'Text 2 would counter the optimism with unresolved questions of judgment and fault.'),
            ('Which choice best describes the relationship between the two texts?',
             ['Text 2 supplies detailed statistics that confirm the claim in Text 1',
               'Text 1 emphasizes a likely benefit while Text 2 emphasizes unresolved concerns',
               'both texts conclude that self-driving cars should be banned outright',
               'both texts agree that the technology is already fully trustworthy'],
             1,
             ['Text 2 raises concerns rather than confirming Text 1 with statistics.',
               'Correct. Text 1 highlights safety benefits; Text 2 highlights open concerns.',
               'Neither text calls for an outright ban.',
               'Text 2 says trust must be earned slowly, not that it is already full.'],
             'Text 1 stresses a benefit; Text 2 stresses unresolved concerns.'),
        ],
    },
    {
        "id": 'wild_fire',
        "text_a": ('Letting some forest fires burn, this author argues, restores a natural cycle: flames clear dead brush, return nutrients to the soil, and let certain seeds, which open only in heat, finally sprout. Fire, the text says, can be a gardener.'),
        "text_b": ("Allowing fires to spread, this author cautions, gambles with homes and lives near the forest's edge, where a shift in wind can turn a managed burn into a disaster. Some risks, the text argues, are too great to accept."),
        "questions": [
            ('Based on the texts, the authors would most likely disagree about whether',
             ['allowing certain forest fires to burn is, on the whole, advisable',
               'fire is capable of consuming dead brush within a forest at all',
               'any people make their homes near the edges of forests',
               'the wind can change direction during the course of a fire'],
             0,
             ['Correct. Text 1 favors letting some fires burn; Text 2 warns the risk is too great.',
               'Both accept that fire consumes brush.',
               'Both accept people live near forests.',
               'Both accept wind can change during a fire.'],
             'Their dispute is whether allowing such fires to burn is advisable.'),
            ("How would the author of Text 2 most likely respond to Text 1's image of fire as 'a gardener'?",
             ['by arguing that even more forests should be deliberately burned',
               'by granting the ecological role but stressing the danger to nearby people',
               'by agreeing that fire poses no threat to homes near the forest',
               'by denying that fire returns any nutrients to the forest soil'],
             1,
             ['Text 2 warns against the risk rather than urging more burning.',
               'Correct. Text 2 acknowledges no benefit explicitly but centers the danger to people near the edge.',
               'Text 2 emphasizes the threat to homes, not its absence.',
               'Text 2 does not dispute the nutrient claim.'],
             'Text 2 would weigh the ecological role against the danger to nearby communities.'),
        ],
    },
    {
        "id": 'ai_art',
        "text_a": ('Image-generating software, the author maintains, is a powerful new tool that lets people without years of training bring their ideas to life. Like the camera before it, the text says, it widens who gets to make pictures.'),
        "text_b": ('Such software, this author objects, is trained on the work of human artists who were neither asked nor paid, and it threatens the very livelihoods that produced the images it learned from. A tool, the text argues, is not neutral about its source.'),
        "questions": [
            ('Based on the texts, the two authors most clearly disagree about whether',
             ['human artists created pictures before such software existed',
               'the camera was an invention that affected how pictures were made',
               'image-generating software is, on balance, a welcome development',
               'the software produces images of any kind when it is used'],
             2,
             ['Both accept human artists made pictures earlier.',
               'Both accept the camera affected picture-making.',
               'Correct. Text 1 welcomes the software; Text 2 objects to its costs to artists.',
               'Both accept the software produces images.'],
             'The dispute is whether the software is, on balance, a welcome development.'),
            ("How would the author of Text 2 most likely respond to Text 1's comparison of the software to the camera?",
             ['by agreeing that the software, like the camera, harms no existing artists',
               'by denying that the camera ever changed who could make pictures',
               'by insisting that no training data is used to build such software',
               "by arguing the comparison overlooks that the software is built from others' uncredited work"],
             3,
             ["Text 2 argues the software threatens artists' livelihoods.",
               "Text 2 does not dispute the camera's historical effect.",
               "Text 2 stresses that the software is trained on artists' work.",
               "Correct. Text 2's key objection is the uncredited, unpaid use of artists' work."],
             "Text 2 would object that the analogy ignores the software's reliance on others' uncredited work."),
        ],
    },
    {
        "id": 'night_light',
        "text_a": ('Brighter streetlights, the author argues, help people feel safe, let drivers see clearly, and keep public spaces usable after dark. Light, the text says, is a basic service a city owes its residents.'),
        "text_b": ('Flooding the night with light, this author warns, wastes energy, disrupts the sleep of people and the movement of nocturnal animals, and erases the stars. Cities, the text suggests, could light only what truly needs it.'),
        "questions": [
            ('Based on the texts, the authors would most likely disagree about whether',
             ['residents of a city ever travel outdoors after sunset',
               'cities should provide abundant artificial light at night',
               'streetlights are able to illuminate a roadway after dark',
               'some animals are active during the nighttime hours'],
             1,
             ['Both accept residents go out after dark.',
               'Correct. Text 1 favors abundant light; Text 2 urges lighting only what is needed.',
               'Both accept streetlights illuminate roads.',
               'Both accept some animals are nocturnal.'],
             'The disagreement is whether cities should provide abundant night light.'),
            ("How would the author of Text 2 most likely respond to Text 1's claim that light is 'a basic service a city owes its residents'?",
             ['by claiming that artificial light cannot affect the sleep of animals',
               'by insisting that cities should make every street far brighter still',
               'by agreeing some light is owed but arguing against flooding the night with it',
               'by denying that residents have any need for streetlights at all'],
             2,
             ['Text 2 explicitly cites disrupted animal movement and sleep.',
               'Text 2 opposes, rather than urges, ever-brighter streets.',
               'Correct. Text 2 would accept lighting what truly needs it while opposing excess.',
               'Text 2 suggests lighting what needs it, not no light at all.'],
             'Text 2 would grant a need for some light yet reject lighting in excess.'),
        ],
    },
    {
        "id": 'ancient_diet',
        "text_a": ('To understand what ancient people ate, this author argues, nothing beats studying their bones and teeth directly, since the chemistry left in them records a lifetime of meals. The body itself, the text says, keeps the most honest diary.'),
        "text_b": ('Bones tell only part of the story, this author counters. Tools, cooking pits, and the charred remains of plants reveal foods that leave no trace in the skeleton. The fullest picture, the text argues, comes from the whole site, not the body alone.'),
        "questions": [
            ('Based on the texts, the authors would most likely disagree about whether',
             ['ancient people ate food of some kind during their lives',
               'tools and cooking pits can be found at ancient sites',
               'chemistry can be measured in ancient bones and teeth',
               'studying bones alone gives the best account of an ancient diet'],
             3,
             ['Both accept ancient people ate food.',
               'Both accept tools and pits exist at sites.',
               'Both accept bone chemistry can be measured.',
               'Correct. Text 1 favors bones as the best source; Text 2 says the whole site is needed.'],
             'The dispute is whether bones alone best reveal an ancient diet.'),
            ('How does Text 2 respond to the central claim of Text 1?',
             ['it argues that bones miss foods revealed only by other site evidence',
               'it agrees that bones are the single most complete source of diet data',
               'it denies that bone chemistry preserves any record of past meals',
               'it claims that ancient sites contain no remains of plants at all'],
             0,
             ['Correct. Text 2 says bones miss foods that tools and charred plants reveal.',
               'Text 2 disputes that bones alone are most complete.',
               'Text 2 does not deny bone chemistry records meals.',
               'Text 2 cites charred plant remains as evidence.'],
             'Text 2 responds that bones overlook foods other site evidence can reveal.'),
        ],
    },
    {
        "id": 'gig_work',
        "text_a": ('App-based gig work, the author argues, offers flexibility that traditional jobs rarely match: workers choose their own hours and can earn around other commitments. For many, the text says, that freedom is the whole appeal.'),
        "text_b": ('That freedom, this author replies, often comes without the protections of steady employment, such as sick pay or a guaranteed wage. Flexibility, the text warns, can quietly shift risk from the company onto the worker.'),
        "questions": [
            ('Based on the texts, the two authors most clearly disagree about whether',
             ['some workers have commitments outside of their paid work',
               'traditional jobs typically set fixed hours for employees',
               'the flexibility of gig work is, on balance, a good deal for workers',
               'gig workers use an app of some kind to find available work'],
             2,
             ['Both accept workers have outside commitments.',
               'Both accept traditional jobs set fixed hours.',
               'Correct. Text 1 praises the flexibility; Text 2 warns it shifts risk to workers.',
               'Both accept gig work is app-based.'],
             'The dispute is whether gig flexibility is, on balance, a good deal.'),
            ("How would the author of Text 2 most likely respond to Text 1's emphasis on freedom?",
             ['by agreeing that gig work carries no risks or drawbacks for workers',
               'by denying that gig workers can ever set their own working hours',
               'by claiming that traditional jobs offer no protections to employees',
               'by acknowledging the freedom but noting it often lacks key protections'],
             3,
             ['Text 2 highlights risks rather than denying them.',
               'Text 2 does not dispute that workers choose hours.',
               'Text 2 contrasts gig work with the protections of steady jobs.',
               'Correct. Text 2 grants the flexibility yet stresses missing protections like sick pay.'],
             'Text 2 would concede the freedom while stressing the lost protections.'),
        ],
    },
    {
        "id": 'museum_return',
        "text_a": ('Great museums, the author argues, gather treasures from many cultures under one roof, letting visitors study the whole human story in a single visit. That shared access, the text says, belongs to everyone.'),
        "text_b": ("Many of those treasures, this author notes, were taken from their homelands during periods of conquest, often without consent. Returning them, the text argues, respects the communities that created them, even at the cost of a museum's completeness."),
        "questions": [
            ('Based on the texts, the authors would most likely disagree about whether',
             ['museums should keep objects gathered from many different cultures',
               'museums display objects that visitors can come to see',
               "some museum objects originated in places outside the museum's country",
               'people from various cultures created artworks in the past'],
             0,
             ['Correct. Text 1 defends keeping such collections; Text 2 argues for returning many objects.',
               'Both accept museums display objects.',
               'Both accept objects came from elsewhere.',
               'Both accept various cultures created art.'],
             'The dispute is whether museums should keep objects gathered from many cultures.'),
            ("How would the author of Text 2 most likely respond to Text 1's praise of shared access 'for everyone'?",
             ['by insisting that visitors gain nothing from seeing objects in a museum',
               'by arguing that access does not justify keeping objects taken without consent',
               'by agreeing that completeness should outweigh the wishes of source communities',
               'by denying that museums hold any objects from outside their own borders'],
             1,
             ['Text 2 does not claim visitors gain nothing.',
               'Correct. Text 2 would say shared access cannot justify retaining objects taken without consent.',
               'Text 2 prioritizes source communities over completeness.',
               'Text 2 stresses that many objects came from elsewhere.'],
             'Text 2 would answer that broad access does not justify keeping objects taken without consent.'),
        ],
    },
]
