"""Additional original authored pools for SAT Reading & Writing practice.

These extend the curated lists in rw_gen.py with more original items, matching
the exact tuple formats used there:

  * TRANS2      -> same shape as rw_gen._TRANS_ITEMS:
                  (sentence1, sentence2, relation)
  * CONCISION2  -> same shape as rw_gen._CONCISION:
                  (concise, wordy1, wordy2, wordy3)
  * SYNTH2      -> same shape as rw_gen._SYNTHESIS:
                  (topic, notes_list, goal, correct_sentence, distractors_list)

All content is original. No sentence or idea here duplicates rw_gen.py.
"""
from __future__ import annotations

# --------------------------------------------------------------------------- #
# Transitions: (sentence1, sentence2, relation)
# relation in {contrast, cause, addition, example, sequence, emphasis}
# sentence1 ends with a period; sentence2 is a lowercase clause that follows
# "<s1> ___, <s2>".
# --------------------------------------------------------------------------- #
TRANS2 = [
    ("Tidal turbines generate power around the clock.", "they run even when the wind is calm and the sky is dark.", "cause"),
    ("The mayor pledged to plant a thousand street trees.", "the budget covered only a few dozen of them.", "contrast"),
    ("Octopuses can change color in an instant.", "they can also reshape their skin to mimic rough coral.", "addition"),
    ("Antarctica holds most of the planet's fresh water.", "it is locked away in a vast sheet of ice.", "cause"),
    ("The startup ran out of cash by the spring.", "its founders sold the patents to a rival.", "sequence"),
    ("Honeybees communicate the location of food.", "a scout performs a looping dance on the comb.", "example"),
    ("The committee debated the proposal for hours.", "it adjourned without reaching a decision.", "sequence"),
    ("The desert receives almost no rainfall.", "a surprising number of plants flourish there.", "contrast"),
    ("The factory recycles nearly all of its scrap metal.", "it sends very little waste to the landfill.", "cause"),
    ("The novel was rejected by a dozen publishers.", "it went on to win the country's top literary prize.", "contrast"),
    ("Lighthouses once guided ships along the rocky coast.", "many of them now stand empty and automated.", "contrast"),
    ("The river floods the valley every few years.", "farmers there expect the rich silt it leaves behind.", "cause"),
    ("The choir auditioned new singers in the fall.", "it began rehearsing the holiday program in October.", "sequence"),
    ("Sloths move slowly through the rainforest canopy.", "their fur hosts tiny algae that help them blend in.", "addition"),
    ("The clinic offered free screenings on weekends.", "turnout exceeded every projection.", "cause"),
    ("The professor warned that the proof was incomplete.", "no flaw in it has ever been found.", "contrast"),
    ("Volcanic ash can blanket fields for miles.", "it eventually enriches the soil it once smothered.", "contrast"),
    ("The team gathered its supplies at base camp.", "it set out for the summit before dawn.", "sequence"),
    ("The new alloy resists rust remarkably well.", "shipbuilders have begun ordering it in bulk.", "cause"),
    ("The lecture was supposed to last an hour.", "it stretched well past lunchtime.", "contrast"),
    ("The archive holds letters from the founding era.", "it preserves diaries, maps, and old ledgers as well.", "addition"),
    ("The vaccine took years to develop.", "researchers screened thousands of candidate compounds.", "example"),
    ("The drought withered the corn in July.", "yields fell to their lowest level in a decade.", "cause"),
    ("The painting looked dull under the old lights.", "the restored gallery revealed its vivid colors.", "contrast"),
    ("The crew dismantled the old stage on Monday.", "they assembled the new set by Friday.", "sequence"),
    ("Some spiders spin silk stronger than steel by weight.", "engineers study it to design tougher fabrics.", "cause"),
    ("The candidate promised to lower the city's debt.", "spending climbed in her first year in office.", "contrast"),
    ("The garden draws bees throughout the summer.", "it shelters frogs and dragonflies near the pond.", "addition"),
    ("The bridge cannot bear heavy trucks anymore.", "freight must now take the longer route around the gorge.", "cause"),
    ("The hikers misread the trail map at noon.", "they ended up on the far side of the ridge by dusk.", "cause"),
    ("Glaciers carved these valleys long ago.", "they left behind smooth walls and scattered boulders.", "cause"),
    ("The director cut three scenes from the film.", "the pacing felt far tighter as a result.", "cause"),
    ("The museum charges no admission fee.", "it asks visitors to leave whatever they can.", "addition"),
    ("The orchard suffered a late frost in April.", "only a fraction of the trees bore fruit.", "cause"),
    ("The report flagged several gaps in the data.", "it recommended a follow-up survey for each one.", "addition"),
    ("The robot could not climb the steep ramp.", "engineers redesigned its wheels and tried again.", "sequence"),
    ("Tap water in the town tasted faintly of iron.", "residents had complained about it for years.", "emphasis"),
    ("The migration covers thousands of miles.", "some birds fly nonstop for days without resting.", "emphasis"),
    ("The print run sold out within a week.", "the publisher rushed a second edition to stores.", "cause"),
    ("The seeds need cold weather to sprout.", "gardeners chill them in a refrigerator first.", "cause"),
]


# --------------------------------------------------------------------------- #
# Concision: (concise, wordy1, wordy2, wordy3)
# First entry is the best concise clause (no trailing period, lowercase start).
# The other three are wordy/redundant rewrites of the SAME idea.
# --------------------------------------------------------------------------- #
CONCISION2 = [
    ("the comet returns every 76 years", "the comet returns and comes back every 76 years on a regular cycle",
     "the comet, in terms of timing, returns every 76 years",
     "every 76 years is the interval at which the comet returns again"),
    ("the council canceled the parade", "the council canceled and called off the planned parade entirely",
     "the council, after some debate, canceled the parade",
     "the parade was canceled by the council that decided against it"),
    ("the glacier is retreating rapidly", "the glacier is retreating and shrinking back rapidly and fast",
     "the glacier, which is enormous, is retreating rapidly",
     "rapid retreat is what the glacier is currently undergoing quickly"),
    ("the clinic vaccinated hundreds of children", "the clinic vaccinated and immunized hundreds of young children",
     "the clinic, open all week, vaccinated hundreds of children",
     "hundreds of children were vaccinated by the clinic that treated them"),
    ("the engineer simplified the design", "the engineer simplified and streamlined the overly complex design",
     "the engineer, working late, simplified the design",
     "the design was simplified by the engineer who refined it"),
    ("the orchard yields apples in October", "the orchard yields and produces apples in the month of October",
     "the orchard, planted years ago, yields apples in October",
     "October is the month during which the orchard yields its apples"),
    ("the satellite mapped the ocean floor", "the satellite mapped and charted the entire ocean floor below",
     "the satellite, high above, mapped the ocean floor",
     "the ocean floor was mapped by the satellite that surveyed it"),
    ("the crowd cheered the final goal", "the crowd cheered and roared at the last final goal",
     "the crowd, packed in tightly, cheered the final goal",
     "the final goal was cheered by the crowd that celebrated it"),
    ("the trail climbs steeply to the peak", "the trail climbs and ascends steeply up to the high peak",
     "the trail, which is rugged, climbs steeply to the peak",
     "a steep climb to the peak is what the trail involves upward"),
    ("the author abandoned the sequel", "the author abandoned and gave up on the planned sequel",
     "the author, frustrated at last, abandoned the sequel",
     "the sequel was abandoned by the author who dropped it"),
    ("the dam controls seasonal flooding", "the dam controls and manages the recurring seasonal flooding",
     "the dam, built decades ago, controls seasonal flooding",
     "seasonal flooding is controlled by the dam that holds it back"),
    ("the chef seasoned the broth lightly", "the chef seasoned and flavored the broth in a light, subtle way",
     "the chef, tasting as she went, seasoned the broth lightly",
     "the broth was lightly seasoned by the chef who flavored it"),
    ("the storm knocked out the power", "the storm knocked out and cut off the electrical power completely",
     "the storm, which was fierce, knocked out the power",
     "the power was knocked out by the storm that disrupted it"),
    ("the library lends musical instruments", "the library lends and loans out musical instruments to borrowers",
     "the library, in a new program, lends musical instruments",
     "musical instruments are lent by the library that offers them"),
    ("the bees pollinate the orchard", "the bees pollinate and fertilize the flowering orchard trees",
     "the bees, busy all day, pollinate the orchard",
     "the orchard is pollinated by the bees that visit it"),
    ("the tunnel shortens the drive", "the tunnel shortens and reduces the length of the long drive",
     "the tunnel, recently bored, shortens the drive",
     "the drive is shortened by the tunnel that cuts through the hill"),
    ("the volcano erupted last spring", "the volcano erupted and blew its top last spring season",
     "the volcano, dormant for years, erupted last spring",
     "last spring was when the volcano went ahead and erupted"),
    ("the editor trimmed the article", "the editor trimmed and cut down the lengthy, wordy article",
     "the editor, pressed for space, trimmed the article",
     "the article was trimmed by the editor who shortened it"),
    ("the spacecraft orbits the moon", "the spacecraft orbits and circles around the distant moon",
     "the spacecraft, far from Earth, orbits the moon",
     "the moon is orbited by the spacecraft that circles it"),
    ("the workshop teaches basic coding", "the workshop teaches and instructs students in basic, fundamental coding",
     "the workshop, held on weekends, teaches basic coding",
     "basic coding is taught at the workshop that covers it"),
    ("the dye fades in sunlight", "the dye fades and loses its color in bright sunlight outdoors",
     "the dye, which is cheap, fades in sunlight",
     "fading in sunlight is something the dye does over time"),
    ("the ferry crosses the bay hourly", "the ferry crosses and traverses the wide bay each and every hour",
     "the ferry, painted blue, crosses the bay hourly",
     "the bay is crossed by the ferry that runs every hour"),
    ("the scientist measured the rainfall", "the scientist measured and recorded the amount of the rainfall",
     "the scientist, with a gauge, measured the rainfall",
     "the rainfall was measured by the scientist who gauged it"),
    ("the crew patched the leaking roof", "the crew patched and sealed up the leaking, dripping roof",
     "the crew, working fast, patched the leaking roof",
     "the leaking roof was patched by the crew that fixed it"),
    ("the algorithm sorts the records quickly", "the algorithm sorts and orders the records quickly and fast",
     "the algorithm, newly written, sorts the records quickly",
     "quick sorting of the records is what the algorithm does rapidly"),
    ("the park bans motor vehicles", "the park bans and forbids the use of motor vehicles entirely",
     "the park, popular with families, bans motor vehicles",
     "motor vehicles are banned in the park that prohibits them"),
    ("the violinist tuned her instrument", "the violinist tuned and adjusted her instrument carefully",
     "the violinist, before the show, tuned her instrument",
     "her instrument was tuned by the violinist who readied it"),
    ("the comet brightened near the sun", "the comet brightened and grew more luminous as it neared the sun",
     "the comet, watched by many, brightened near the sun",
     "brightening near the sun is what the comet did as it approached"),
    ("the tide exposes the tidal pools", "the tide exposes and reveals the rocky tidal pools below",
     "the tide, going out twice daily, exposes the tidal pools",
     "the tidal pools are exposed by the tide that recedes from them"),
    ("the farmer rotates the crops yearly", "the farmer rotates and alternates the crops on a yearly basis",
     "the farmer, mindful of the soil, rotates the crops yearly",
     "the crops are rotated by the farmer who alternates them each year"),
    ("the firm relocated to the coast", "the firm relocated and moved its offices to the distant coast",
     "the firm, seeking talent, relocated to the coast",
     "the coast is where the firm decided to relocate its operations"),
    ("the lecture clarified the theorem", "the lecture clarified and explained the difficult theorem clearly",
     "the lecture, given Tuesday, clarified the theorem",
     "the theorem was clarified by the lecture that explained it"),
    ("the reservoir supplies the city", "the reservoir supplies and provides water to the entire city",
     "the reservoir, high in the hills, supplies the city",
     "the city is supplied with water by the reservoir that feeds it"),
    ("the puppy chewed the new shoes", "the puppy chewed and gnawed on the brand-new leather shoes",
     "the puppy, left alone, chewed the new shoes",
     "the new shoes were chewed by the puppy that destroyed them"),
    ("the survey reached rural households", "the survey reached and made contact with remote rural households",
     "the survey, mailed out widely, reached rural households",
     "rural households were reached by the survey that surveyed them"),
    ("the kiln hardens the clay pots", "the kiln hardens and fires the soft, wet clay pots solid",
     "the kiln, fired all night, hardens the clay pots",
     "the clay pots are hardened by the kiln that bakes them"),
    ("the cyclist won the mountain stage", "the cyclist won and took first place in the grueling mountain stage",
     "the cyclist, despite the heat, won the mountain stage",
     "the mountain stage was won by the cyclist who led it"),
    ("the wetland filters the runoff", "the wetland filters and cleans the polluted runoff water",
     "the wetland, full of reeds, filters the runoff",
     "the runoff is filtered by the wetland that purifies it"),
    ("the gallery sold every print", "the gallery sold and managed to sell off every single print",
     "the gallery, busy that night, sold every print",
     "every print was sold by the gallery that exhibited them"),
    ("the antenna receives faint signals", "the antenna receives and picks up extremely faint, weak signals",
     "the antenna, mounted high, receives faint signals",
     "faint signals are received by the antenna that detects them"),
]


# --------------------------------------------------------------------------- #
# Rhetorical synthesis:
# (topic, notes_list, goal, correct_sentence, distractors_list)
# notes_list: 3-4 short bullet facts; distractors_list: exactly 3 full sentences
# that are accurate but do NOT meet the goal, matched roughly in length to the
# correct sentence.
# --------------------------------------------------------------------------- #
SYNTH2 = [
    ("a vertical farm",
     ["The farm grows lettuce in stacked indoor trays.",
      "It uses 95% less water than a field.",
      "It produces greens year-round in any weather."],
     "emphasize the water savings",
     "By growing lettuce in stacked indoor trays, the farm produces year-round greens while using 95% less water than a field.",
     ["Because it operates entirely indoors, the vertical farm can produce fresh greens during every season of the year.",
      "The farm relies on stacked trays of lettuce arranged in tall rows inside a carefully controlled indoor space.",
      "Vertical farming, a method of growing crops in stacked layers, is being tried in cities short on open land."]),
    ("a meteor shower",
     ["The shower peaks in mid-August each year.",
      "Viewers may see up to 60 meteors an hour.",
      "It is caused by debris from an old comet."],
     "explain what causes the shower",
     "The August shower occurs as Earth passes through the dusty trail of an old comet, where bits of debris burn up as meteors.",
     ["At its peak in mid-August, the shower can treat patient viewers to as many as sixty meteors every single hour.",
      "Anyone hoping to catch the show should find a dark spot in mid-August and let their eyes adjust to the night sky.",
      "A meteor, often called a shooting star, is a streak of light made when a particle burns up in the atmosphere."]),
    ("a city composting program",
     ["Residents sort food scraps into green bins.",
      "The scraps become compost for public parks.",
      "The program cut landfill waste by a fifth."],
     "report the program's main result",
     "Since residents began sorting food scraps into green bins, the city has cut the waste sent to its landfill by a fifth.",
     ["Across the city, residents now carefully sort their leftover food scraps into the green bins set out for collection.",
      "The compost made from the collected scraps is later spread across the soil of the city's many public parks.",
      "Composting, the natural breakdown of organic matter into rich soil, has long been practiced by home gardeners."]),
    ("a deep-sea expedition",
     ["A submersible reached 6,000 meters down.",
      "It filmed creatures never seen before.",
      "Crushing pressure required a titanium hull."],
     "emphasize the difficulty of the conditions",
     "Withstanding crushing pressure that demanded a titanium hull, the submersible descended 6,000 meters to film creatures never seen before.",
     ["During the dive, the expedition's cameras captured footage of several deep-sea creatures never before seen by anyone.",
      "The submersible used on the expedition was built with a strong titanium hull to keep its crew safe below the surface.",
      "A submersible, a small craft designed for underwater travel, can carry researchers far deeper than ordinary divers go."]),
    ("a wind turbine farm",
     ["The farm has 40 turbines on a ridge.",
      "Each turbine stands 120 meters tall.",
      "Together they power 30,000 homes."],
     "convey the farm's overall scale",
     "Forty turbines, each rising 120 meters along the ridge, together generate enough electricity to power 30,000 homes.",
     ["Standing on the ridge, each of the farm's turbines reaches an impressive height of about one hundred twenty meters.",
      "The forty turbines were installed along a windswept ridge chosen for its steady and reliable seasonal breezes.",
      "A wind turbine, which turns moving air into electricity, has become a familiar sight across many rural landscapes."]),
    ("a historic theater restoration",
     ["The theater opened in 1912.",
      "A fire damaged it badly in 1980.",
      "Donors funded a full restoration this year."],
     "present the building's troubled history",
     "Opened in 1912, the theater was nearly destroyed by a fire in 1980 before donors finally funded a full restoration this year.",
     ["Thanks to a group of generous donors, the theater received a complete restoration during the course of this past year.",
      "When the theater first opened its doors to audiences back in 1912, it quickly became a centerpiece of the town.",
      "A theater, a building made for staging plays and concerts, often serves as a gathering place for a whole community."]),
    ("a freshwater turtle study",
     ["Females nest on the same beach for life.",
      "Warmer sand produces more female hatchlings.",
      "Researchers tagged 200 turtles over five years."],
     "highlight the link between temperature and sex",
     "Because warmer sand produces more female hatchlings, the temperature of a nesting beach can tip a turtle population toward females.",
     ["Over the course of five years, the patient researchers managed to tag and track a total of two hundred turtles.",
      "The female turtles in the study return to nest on the very same stretch of beach throughout their entire lives.",
      "A turtle, a reptile protected by a hard shell, can live for many decades in the right freshwater habitat."]),
    ("a bike commuter survey",
     ["Half of riders started during the pandemic.",
      "Most cite cost savings as their main reason.",
      "Few plan to return to driving."],
     "explain why people took up cycling",
     "Most riders surveyed took up cycling for the savings, and few of them now plan to go back to driving a car.",
     ["According to the survey, roughly half of the city's bike commuters first started riding during the pandemic years.",
      "The survey gathered responses from a broad range of commuters who now travel to work on two wheels each day.",
      "Cycling, an inexpensive and healthy way to get around, has grown more popular in many crowded urban centers."]),
    ("a salt marsh carbon study",
     ["Marsh mud stores carbon for centuries.",
      "An acre traps as much carbon as a forest.",
      "Draining the marsh releases it all at once."],
     "stress the marsh's value for storing carbon",
     "An acre of salt marsh can trap as much carbon as a forest, locking it away in mud for centuries unless the marsh is drained.",
     ["When a salt marsh is drained for development, the carbon it once held is released back into the air all at once.",
      "The dark mud beneath a healthy salt marsh is capable of holding on to stored carbon for many hundreds of years.",
      "A salt marsh, a coastal wetland flooded by the tides, supports crabs, fish, and a wide variety of wading birds."]),
    ("an electric bus rollout",
     ["The agency replaced 50 diesel buses.",
      "The fleet now runs nearly silent.",
      "Riders report a smoother, cleaner ride."],
     "describe how the change affected riders",
     "Now that 50 diesel buses have been replaced, riders enjoy a fleet that runs nearly silent and gives a smoother, cleaner ride.",
     ["In a major shift, the transit agency went ahead and replaced fifty of its aging diesel buses with new models.",
      "The new electric buses move so quietly that pedestrians sometimes fail to hear one approaching the curb.",
      "An electric bus, powered by rechargeable batteries instead of fuel, produces no exhaust as it travels its route."]),
    ("a citizen science app",
     ["Users photograph wild plants and animals.",
      "Experts verify each submitted identification.",
      "The data helped map a rare frog's range."],
     "show how the app advanced real research",
     "After experts verified the photos that users submitted, the app's data helped scientists map the full range of a rare frog.",
     ["Using the app, ordinary people across the region photograph the wild plants and animals they happen to encounter.",
      "Every identification that a user submits through the app is later checked and verified by a qualified expert.",
      "Citizen science, in which volunteers help gather data, lets researchers collect far more observations than usual."]),
    ("a desert solar tower",
     ["Mirrors focus sunlight on a central tower.",
      "Molten salt stores the heat for nightfall.",
      "The plant supplies power after dark."],
     "explain how the plant produces power at night",
     "By storing the sun's heat in molten salt, the tower keeps supplying power well after dark, when ordinary solar panels go quiet.",
     ["A wide field of mirrors surrounds the plant, each one angled to focus sunlight onto the tall central tower.",
      "The tower at the heart of the plant is the point where all of the mirrors direct their concentrated sunlight.",
      "Solar power, drawn from the energy of the sun, can be captured in several different ways across the world."]),
    ("a coral spawning event",
     ["The corals spawn one night each year.",
      "They release eggs in sync with the full moon.",
      "Divers collect the eggs to raise new colonies."],
     "convey the remarkable timing of the spawning",
     "Cued by the full moon, an entire reef of corals releases its eggs on a single synchronized night each year.",
     ["On the night of the spawning, divers carefully gather the floating eggs in order to raise brand-new colonies.",
      "The eggs that the corals release during the event are collected and later used to grow fresh coral colonies.",
      "Coral, a tiny animal that builds a stony skeleton, joins with countless others to form a sprawling living reef."]),
    ("a public seed library",
     ["Gardeners borrow seeds for free.",
      "They return seeds saved from their harvest.",
      "The collection favors local heirloom varieties."],
     "explain how the library sustains itself",
     "The seed library keeps going because gardeners who borrow seeds for free return new ones saved from their own harvests.",
     ["The collection housed at the seed library leans heavily toward heirloom varieties suited to the local climate.",
      "Any gardener in the community is welcome to borrow a packet of seeds from the library at no cost at all.",
      "A seed, the small package from which a plant grows, can stay viable for years if it is stored properly."]),
    ("a river otter comeback",
     ["Otters vanished from the river by 1970.",
      "Cleaner water let fish populations rebound.",
      "Otters returned on their own by 2015."],
     "link the otters' return to the cleaner water",
     "As cleaner water allowed fish populations to rebound, the otters that had vanished by 1970 returned to the river on their own by 2015.",
     ["By the year 1970, river otters had disappeared completely from the waterway that had once been their home.",
      "Wildlife officials were pleased to confirm that otters had come back to the river entirely on their own by 2015.",
      "A river otter, a sleek and playful mammal, hunts fish and crayfish along the banks of streams and rivers."]),
    ("a museum lighting upgrade",
     ["New LED lights replaced old halogen bulbs.",
      "The lights give off far less heat.",
      "Fragile paintings now fade more slowly."],
     "emphasize the benefit to the artwork",
     "Because the new LED lights give off far less heat than the old halogen bulbs, the museum's fragile paintings now fade more slowly.",
     ["As part of the upgrade, the museum swapped out all of its old halogen bulbs for modern, efficient LED lights.",
      "Compared with the bulbs they replaced, the new lights installed throughout the galleries produce noticeably less heat.",
      "A museum, a place that collects and displays objects of interest, must balance public access with careful conservation."]),
    ("a tornado warning system",
     ["New radar detects rotation earlier.",
      "Alerts now arrive minutes sooner.",
      "Earlier warnings save lives."],
     "stress the life-saving value of earlier alerts",
     "By detecting rotation earlier and sending alerts minutes sooner, the new radar gives families precious extra time that saves lives.",
     ["The recently installed radar is able to pick up the rotation inside a storm earlier than the older equipment could.",
      "Thanks to the upgraded system, the warnings now reach people in the storm's path several minutes ahead of before.",
      "A tornado, a violently spinning column of air, can flatten buildings within seconds of touching down on the ground."]),
    ("a school orchard program",
     ["Students planted fruit trees on campus.",
      "They learn pruning and grafting by hand.",
      "The harvest is shared in the cafeteria."],
     "describe what students gain from the program",
     "By planting the campus trees and tending them by hand, students learn pruning and grafting while sharing the harvest at lunch.",
     ["The fruit trees that the students planted now grow in neat rows across one corner of the school's campus.",
      "Whatever fruit the young orchard manages to produce is gathered up and shared with everyone in the cafeteria.",
      "An orchard, a planting of trees grown for their fruit, takes several patient years to reach full production."]),
    ("a peat bog excavation",
     ["The bog preserved a 4,000-year-old canoe.",
      "Low oxygen kept the wood from rotting.",
      "The find reveals ancient travel routes."],
     "explain why the canoe survived so long",
     "Because the bog's waterlogged, low-oxygen mud kept the wood from rotting, a canoe survived there for some 4,000 years.",
     ["The well-preserved canoe pulled from the bog offers fresh clues about the routes ancient people once traveled.",
      "Buried deep in the peat, the canoe turned out to be roughly four thousand years old when experts examined it.",
      "A bog, a soft wetland built up from layers of decaying plants, forms slowly over many thousands of years."]),
    ("a rooftop beehive project",
     ["Hives sit atop a downtown office.",
      "City flowers give bees a long season.",
      "The bees pollinate nearby park gardens."],
     "highlight the benefit to surrounding plants",
     "From their hives atop the downtown office, the bees range out to pollinate the flowering gardens of nearby parks.",
     ["The beehives that anchor the project are set up on the flat rooftop of a tall downtown office building.",
      "Because the surrounding city offers blooms for much of the year, the bees enjoy an unusually long season.",
      "A bee, an insect that gathers nectar and pollen, lives within a hive alongside thousands of its fellow workers."]),
]
